---
############################################################
#    PROJECT  : MALT (MALoc Tracker)
#    VERSION  : 1.3.0
#    DATE     : 09/2024
#    LICENSE  : CeCILL-C
#    FILE     : .gitlab-ci.yml
#-----------------------------------------------------------
#    AUTHOR   : Sébastien Valat - 2015 - 2024
#    AUTHOR   : Sébastien Valat (INRIA) - 2024
############################################################
test:
  script:
  - git submodule update --init
  - ls -la
  - rm -rfv build testinstall
  - mkdir build
  - cd build
  - ../configure --enable-debug --enable-tests --prefix="$PWD/../testinstall" CXXFLAGS="-Werror" CFLAGS="-Werror"
  - make
  - ctest --output-on-failure
  - make install
  tags: 
  except:
  - tags
