test:
  script:
  - git submodule update --init
  - ls -la
  - rm -rfv build testinstall
  - mkdir build
  - cd build
  - ../configure --enable-debug --enable-tests --prefix="$PWD/../testinstall" CXXFLAGS="-Werror" CFLAGS="-Werror"
  - make
  - ctest --output-on-failure
  - make install
  tags: 
  except:
  - tags
