#!/bin/sh
############################################################
#    PROJECT  : MALT (MALoc Tracker)
#    DATE     : 11/2025
#    LICENSE  : CeCILL-C
#    FILE     : options
#-----------------------------------------------------------
#    AUTHOR   : Sébastien Valat - 2018 - 2022
#    AUTHOR   : Sébastien Valat (INRIA) - 2024 - 2025
############################################################

############################################################
#set project name
cfg_set_projet "MALT"

############################################################
#profiler
cfg_add_enable_option --name='profiler' \
						--on='-DENABLE_PROFILER=${ON}' \
						--doc='Disable the profiler and only install the GUI.' \
						--invert-help
#test
cfg_add_enable_option --name='tests' \
						--on='-DENABLE_TESTS=${ON}' \
						--doc='Disable unit tests' \
						--invert-help
#gcc test coverage
cfg_add_enable_option --name='gcc-coverage'  \
						--on='-DENABLE_GCC_COVERAGE=${ON}' \
						--doc='Enable GCC option to generate test coverage of the lib' \
#junit xml out
cfg_add_enable_option --name='junit-output'  \
						--on='-DENABLE_JUNIT_OUTPUT=${ON}' \
						--doc='Save test output in JUnit format (only in self-test mode)' 
#valgrind
cfg_add_enable_option --name='valgrind' \
						--on='-DENABLE_VALGRIND=${ON}' \
						--doc='Enable running unit tests into valgrind to generate reports'
#jenkins full features
cfg_add_enable_option --name='jenkins' \
						--on-enable-inherit='--enable-valgrind --enable-junit-output --enable-debug "CXXFLAGS=-Wall -fprofile-arcs -ftest-coverage"' \
						--doc='Enable all checking modes (unit, valgrind, coverage...)' \
						--only='enable'

#test
cfg_add_enable_option --name='link-optim' \
						--on='-DENABLE_LINK_OPTIM=${ON}' \
						--doc='Disable link optimization (LTO + visibility=hidden).' \
						--invert-help

#test
cfg_add_enable_option --name='ipo' \
						--on='-DENABLE_IPO=${ON}' \
						--doc='Disable LTO specifically.' \
						--invert-help

#test
cfg_add_enable_option --name='python' \
						--on='-DENABLE_PYTHON=${ON}' \
						--doc='Disable the python support.' \
						--invert-help

#JeMalloc built for MALT
cfg_add_enable_option --name='jemalloc' \
						--on='-DENABLE_JEMALLOC=${ON}' \
						--doc='Enable building the internal jemalloc to get better internal memory handling.' \

#profiler
cfg_add_enable_option --name='prefer-embed' \
						--on='-DENABLE_PREFER_EMBED=${ON}' \
						--doc='Prefer using the embedded dependencies instead of search the system onces.'

#caching
cfg_add_enable_option --name='caching' \
						--on='-DENABLE_CACHING=${ON}' \
						--doc='Enable usage of some internal caches to reduce the overhead of MALT.' \
						--invert-help

#caching
cfg_add_enable_option --name='webview-rebuild' \
						--on-enable='-DWEBVIEW_REBUILD=FORCE' \
						--on-disable='-DWEBVIEW_REBUILD=AUTO' \
						--doc='Force rebuilding the webview.'

############################################################
#libunwind
cfg_add_with_option --name='libunwind' \
						--doc='Define prefix to find libunwind [/usr]' \
						--var='LIBUNWIND_PREFIX'

#libelf
cfg_add_with_option --name='libelf' \
						--doc='Define prefix to find libelf [/usr]' \
						--var='LIBELF_PREFIX'

#where to search python
cfg_add_with_option --name='python' \
						--doc='Define prefix to find python [/usr]' \
						--var='Python3_ROOT_DIR'

#iniparser
cfg_add_with_option --name='iniparser' \
						--doc='Define prefix to find iniparser [/usr]' \
						--var='INIPARSER_PREFIX'

#Python linking way for MALT
cfg_add_with_option --name='python-linking' \
						--doc='Define how to link to python (LAZY or NATIVE). [LAZY]' \
						--var='PORTABILITY_PYTHON'

#where to search python
cfg_add_with_option --name='cargo' \
						--doc='Define prefix to find cargo [/usr]' \
						--var='CARGO_PREFIX'

#where to search python
cfg_add_with_option --name='webview' \
						--doc='Define which webview server implementation to use [AUTO] : AUTO, CPP, NODEJS, RUST, OFF' \
						--var='WEBVIEW_SERVER'

#where to search python
cfg_add_with_option --name='nodejs' \
						--doc='Define prefix to find NodeJS [/usr]' \
						--var='NODEJS_PREFIX'

#where to search python
cfg_add_with_option --name='npm' \
						--doc='Define prefix to find NPM [/usr]' \
						--var='NPM_PREFIX'

#where to search graphviz
cfg_add_with_option --name='graphviz' \
						--doc='Define prefix to find DOT from graphviz [/usr]' \
						--var='GRAPHVIZ_PREFIX'

#where to search nm from binutils
cfg_add_with_option --name='nm' \
						--doc='Define prefix to find NM from binutils [/usr]' \
						--var='NM_PREFIX'

cfg_add_with_option --name='node-modules' \
						--doc='Define which node_modules to use (AUTO, DOWNLOAD, SYSTEM) [AUTO]' \
						--var='WEBVIEW_DEPS'

############################################################
#If we want to document extra options
#CFG_CUSTOM_HELP="My custom options:"

############################################################
# here we can parse our own options if we want
# Vars available are :
#  - $arg : full argument (eg. --with-gcc=gcc)
#  - $val : value after first '=', egg 'gcc'
#  - $ON $OFF, $ENABLE, $DISABLE, $WIDTH, $WITHOUT
#cfg_parse_custom_opts()
#{
#	return 1
#}

############################################################
#pre check to ease error messages
#All cmake vars are loaded in memory as OPT_* (OPT_CMAKE_C_FLAGS)
#cfg_custom_pre_check()
#{
#	return 1
#}
