.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "MALT\-PASSWD" "1" "October 2025" ""
.SH "NAME"
\fBmalt\-passwd\fR \- Password editor for MALT web GUI
.SH "SYNOPSIS"
\fBmalt\-passwd\fR {username} [password]
.SH "DESCRIPTION"
The MALT web GUI provided by malt\-webview(1) is secured by a local password which is configured by \fBmalt\-passwd\fR command and stored into \fB~/\.malt/passwd\fR file\. It will be called automatically the first time you call \fBmalt\-webview\fR\.
.P
\fBmalt\-passwd\fR is essentially a wrapper to call a script provided by nodeJS module \fBhtpasswd\fR so it also supports all the options it provides\. You can refer to the documentation of this module for more details : https://www\.npmjs\.com/package/htpasswd\.
.SH "ENVIRONMENT"
.TP
\fBMALT_NODEJS\fR
Can be setup to tell which nodeJS to use if the script cannot find it by itself\.
.SH "VERSION"
This is the manpage of MALT version 1\.4\.1\.
.SH "SEE ALSO"
malt\-webview(1), malt(1)
