############################################################
#    PROJECT  : MALT (MALoc Tracker)
#    DATE     : 07/2025
#    LICENSE  : CeCILL-C
#    FILE     : src/reader/webview-2-rust/Cargo.toml
#-----------------------------------------------------------
#    AUTHOR   : Sébastien Valat (INRIA) - 2025
############################################################

############################################################
[package]
name = "malt-webview-rust"
version = "0.0.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
actix-files = "0.6.6"
serde = { version = "1.0", default-features = false, features = ["alloc", "derive"] }
clap = { version = "4.5.39", features = ["derive"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
pretty_assertions = { version = "1.4.1", features = ["alloc"] }
