############################################################
#    PROJECT  : MALT (MALoc Tracker)
#    DATE     : 07/2025
#    LICENSE  : CeCILL-C
#    FILE     : packaging/Dockerfile-debian
#-----------------------------------------------------------
#    AUTHOR   : Sébastien Valat - 2019 - 2024
#    AUTHOR   : Sébastien Valat (INRIA) - 2025
############################################################

#distri we want
FROM debian:trixie

#workdir
WORKDIR /workdir
ENV IN_DOCKER yes

#get list of packages
RUN apt-get update

#install deps
RUN apt-get install -y build-essential make gcc cmake g++ git
RUN apt-get install -y libunwind-dev libelf-dev
RUN apt-get install -y pbuilder debootstrap devscripts cdbs debhelper

