#distri we want
FROM fedora:30

#workdir
WORKDIR /workdir
ENV IN_DOCKER yes

## RHEL/CentOS 7 64-Bit ##
#RUN yum update
#RUN yum install -y wget
#RUN wget http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
#RUN rpm -ivh epel-release-latest-7.noarch.rpm

#get list of packages
RUN yum update -y
#RUN yum upgrade -y

#install deps
RUN yum install -y make gcc gcc-c++ cmake git
RUN yum install -y libunwind-devel elfutils-devel 
RUN yum install -y rpm-build rpmdevtools
RUN yum install -y qt5-qtwebkit-devel
#RUN yum install -y --enable-repo epel qt5-qtwebkit-devel
