############################################################
#    PROJECT  : MALT (MALoc Tracker)
#    VERSION  : 1.2.5
#    DATE     : 02/2025
#    LICENSE  : CeCILL-C
#    FILE     : packaging/Dockerfile-debian
#-----------------------------------------------------------
#    AUTHOR   : Sébastien Valat - 2019 - 2024
############################################################

#distri we want
FROM debian:bookworm

#workdir
WORKDIR /workdir
ENV IN_DOCKER yes

#get list of packages
RUN apt-get update

#install deps
RUN apt-get install -y build-essential make gcc cmake g++ git
RUN apt-get install -y libunwind-dev libelf-dev libqt5webkit5-dev
RUN apt-get install -y pbuilder debootstrap devscripts cdbs debhelper

